In [19]:
import cv2

In [20]:
import numpy as np
import pandas as pd

In [21]:
## Recording your faces, make sure no one else is near the screen
dt={}
sount=0
while True:
    inp=input("enter name: ")
    dt[sount]=inp
    count=0
    z=np.zeros((1,30000))
    cap=cv2.VideoCapture(0)
    cap1=cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")
    while True:
        count=count+1
        ret,frame=cap.read()
        if ret==False:
            continue
        pic=cap1.detectMultiScale(frame,1.1,5)
        offset=0
        lst=[]
        for (x,y,w,h) in pic:
            cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)
            frme=frame[y-offset:y+h+offset,x-offset:x+h+offset]
            frme=cv2.resize(frme,(100,100))
            frme=frme.reshape((1,30000))
            z=np.vstack((z,frme))
            print(z.shape,type(z),'##')
        print(frame.shape)
        cv2.imshow('caption',frame)
        esc_key=cv2.waitKey(1) & 0XFF
        if esc_key==ord('q'):
            df=pd.DataFrame(z)
            print(df.head(5))
            name='sub'+str(sount)+'.csv'
            print(name)
            df.to_csv(name,index=False)
            break
        if z.shape[0]==30:
            df=pd.DataFrame(z)
            print(df.head(5))
            name='sub'+str(sount)+'.csv'
            print(name)
            df.to_csv(name,index=False)
            break
    cap.release()
    cv2.destroyAllWindows()
    sount=sount+1
    ques=input("wanna continue? (Y/N) ")
    if ques=='n':
        break

enter name: Ma
(2, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(3, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(4, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(5, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(6, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(7, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(8, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(9, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(10, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(11, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(12, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(13, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(480, 640, 3)
(14, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(480, 640, 3)
(15, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(16, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(17, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(18, 30000) <class 'numpy.ndarray'> ##
(480, 640, 3)
(19, 300

In [4]:
tt=pd.read_csv('sub0.csv')
tt.shape

(30, 30000)

In [22]:
## All inputs need to be made in the form of matrices
def dist(X,q_p):
    a=np.zeros((1,1))
    mat=((X-q_p)*(X-q_p).T)
    print(mat.shape)
    (r,c)=mat.shape
    if r==c:
        for i in np.arange(0,r,1):
            a=np.vstack((a,mat[i,i]))
        print(a[1:,:],"here")
        return a[1:,:]
def knn(X,y,q_p,k=5,batch=29):
    f_mat=np.zeros((1,2))
    lst=[]
    for i in range(0,int(X.shape[0]/batch),1):
        d_val=dist(X[i*batch:(i+1)*batch,:],q_p)
        print(d_val.shape)
        matrix=np.mat(d_val.reshape((-1,1)))
        n_mat=np.hstack((matrix,y[i*batch:(i+1)*batch,0]))
        f_mat=np.vstack((f_mat,n_mat))
    print(f_mat,"f_mat")
    print(f_mat.shape)
    lst99=[]
    for i in range(0,f_mat.shape[0],1):
        lst99.append((f_mat[i,0],f_mat[i,1]))
    lst99=sorted(lst99)[:k]
    lst45=[]
    ## the part below can be implemented with a numpy array, however since no. of elements are less, I used dict and list :).
    for (a,b) in lst99:
        lst45.append(b)
    dt22={}
    for i in lst45:
        dt22[i]=dt22.get(i,0)+1
    max_ele=max(dt22.values())
    for i in dt22.keys():
        if dt22[i]==max_ele:
            print(i)
            return i

In [23]:
#dt={0:'',1:'Ma'}
lst07=[]
#sount=2
for i in range(0,sount,1):
    text='sub'+str(i)+'.csv'
    lst07.append(text)
zzz=np.zeros((1,30000))
zzz1=np.zeros((1,1))
for i in range(len(lst07)):
    tt=pd.read_csv(lst07[i])
    tt=tt.values
    zz=np.mat(tt[1:30])
    mat1=np.mat(np.ones((zz.shape[0],1)))*i
    zzz=np.vstack((zzz,zz))
    zzz1=np.vstack((zzz1,mat1))
row=zzz.shape[0]
zzz=zzz[1:row,:]
zzz1=zzz1[1:row,:]

cap=cv2.VideoCapture(0)
cap1=cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")
while True:
    ret,frame=cap.read()
    if ret==False:
        continue
    pic=cap1.detectMultiScale(frame,1.1,5)
    for (x,y,w,h) in pic:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)
        frme=frame[y:y+h,x:x+h]
        frme=cv2.resize(frme,(100,100))
        frme=np.mat(frme.reshape((1,30000)))
        ticks=knn(zzz,zzz1,frme)
        name=dt[ticks]
        cv2.putText(frame,name,(x,y),cv2.FONT_HERSHEY_SCRIPT_SIMPLEX,1,(255,255,0),2,cv2.LINE_4)
    cv2.imshow('frame',frame)
    esc_key=cv2.waitKey(10) & 0XFF
    if esc_key==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

(29, 29)
[[5.96581870e+07]
 [5.56899630e+07]
 [5.45860410e+07]
 [4.98684380e+07]
 [5.14511190e+07]
 [6.45173970e+07]
 [8.50087530e+07]
 [9.35984420e+07]
 [1.00881652e+08]
 [1.05173379e+08]
 [1.11552233e+08]
 [1.16332708e+08]
 [1.13834431e+08]
 [1.22163702e+08]
 [1.17122121e+08]
 [1.12393667e+08]
 [1.09056121e+08]
 [9.91370230e+07]
 [8.59112640e+07]
 [7.90255190e+07]
 [7.01735780e+07]
 [6.35523830e+07]
 [6.05287850e+07]
 [5.82643870e+07]
 [5.76045350e+07]
 [5.53295260e+07]
 [5.56693800e+07]
 [5.50338980e+07]
 [5.44953450e+07]] here
(29, 1)
(29, 29)
[[68117294.]
 [69967765.]
 [69099252.]
 [71536186.]
 [68160113.]
 [73208148.]
 [70061000.]
 [70258622.]
 [72140265.]
 [72741425.]
 [71991736.]
 [70543111.]
 [71958322.]
 [73128347.]
 [73374205.]
 [71424760.]
 [72071137.]
 [71988496.]
 [74019308.]
 [72858809.]
 [70941821.]
 [73432248.]
 [74813720.]
 [74376575.]
 [73853101.]
 [72264507.]
 [71138881.]
 [70543434.]
 [73197566.]] here
(29, 1)
[[0.00000000e+00 0.00000000e+00]
 [5.96581870e+07 0.000

In [7]:
cap.release()

zzz1.shape

mm=tt.values
mm[1:30]

sount

dt

y=3
mat1=np.mat(np.ones((matrix.shape[0],1)))*y
mat1

In [10]:
zzz1

matrix([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [11]:
zzz1.shape

(58, 1)

In [12]:
zzz.shape

(58, 30000)